name: flowt
description: "Flowt — A minimal, beautiful notes app that connects thoughts."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.1
  uuid: ^4.2.2
  path_provider: ^2.1.3  # ✅ needed for your image persistence
  # (optional) permission_handler — remove if not used
  # permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
